sudo: required
dist: trusty

language: node_js
node_js:
  - "7"

addons: 
  sonarcloud:
    organization: "sagar2366-github"

services: 
  - docker

before_install:
  - npm install -g http
  - npm install npm@latest -g
  - npm install -g -unsafe-perm jfrog-cli-go

script:
  sonar-scanner

cache:
  directories:
    - "node_modules"
    - ".scannerwork"

deploy:
  provider: script
  script: bash scripts/dockercommands.sh