sudo: required
#dist: trusty

language: node_js
node_js:
  - "7"

addons: 
  sonarcloud:
    organization: "sagar2366-github"

services: 
  - docker

before_install:
  - npm install -g http
  # - npm install npm@latest -g
  # - npm install -g -unsafe-perm jfrog-cli-go
  - docker ps
  # - docker pull docker.artifactory/ubuntu:latest
  # - docker login docker.artifactory -u "admin" -p "Utekar@2366"
  # - docker tag hello-world docker.artifactory/ubuntu:latest
  # - docker push docker.artifactory/ubuntu:latest

script:
  - sonar-scanner
  - wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.7.1/jfrog-cli-linux-amd64/jfrog
  - chmod +x jfrog
  - ping -c 2 192.168.33.18
  - curl -I -k -v http://192.168.33.18:8081/artifactory/api/system/ping
  - ./jfrog rt config --url http://192.168.33.18/artifactory --user admin --password admin new-server1
# - ./jfrog rt u "multi*/*.jar" travisci-generic-local --build-name=travisci-generic-artifactory --build-number=$TRAVIS_BUILD_NUMBER --flat=false

# cache:
#   directories:
#     - "node_modules"
#     - ".scannerwork"

# deploy:
#   provider: script
#   script: bash scripts/dockercommands.sh
